function [ regions ] = extractRegionsbyColorset( indexImg, colorSet, q_size, t0, t1 )

regions = {};
numofRegions = 0;

[height, width] = size(indexImg);

ta = height * width * t0; % this value determines the smallest region can be extracted 1024 = 32 * 32
tb = height * width * t1; % this value determines the smallest contribution(area generated by this color) of each color in colorSet 

tc = 0.2;

B = backRejection(indexImg, colorSet);
B = medfilt2(B, [5, 5]);

[L, n] = bwlabel(B);
numColors = sum(colorSet);

for i = 1 : n
    % check for threshold of region size
    if sum(sum(L == i)) >= ta
        vL = L(:);
        %index = 1 : length(vL);
        vImg = indexImg(:);
        counts = histogram(vImg(vL == i));
        
        counts;
        sum(colorSet);
        
        % check for threshold of color contribution
        if sum(counts >= tb) >= numColors
            p = sum(counts) * 0.2;
            % check the contribution rate
            if sum(counts >= p) >= numColors
                numofRegions = numofRegions + 1;
                % region pass all the tests
                regions{numofRegions} = (L == i);
                
                %figure;
                %imshow(regions{numofRegions});
            end
        end
    end
end

%figure;
%imshow(uint8(255 * L / n));

numofRegions;

end

